version: '3'

services:
  database:
    image: ghusta/postgres-world-db
    ports:
      - 5432:5432

  web:
    build: ./country-web-app
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database